-- tabla de usuarios
create table "user"(
  Id int generated by default as identity primary key,
  Email varchar(50) not null unique,
  Password varchar(255) not null,
  Availability smallint default 1,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now()
);

--tabla de roles
create table role(
  Id int generated by default as identity primary key,
  Name varchar(50) not null unique
);

--tabla de posiciones
create table position(
  Id int generated by default as identity primary key,
  Name varchar(50) not null unique,
  Description text
);

--tabla de torneos
create table tournament(
  Id int generated by default as identity primary key,
  Name varchar(50) not null unique,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now()
);

--tabla de temporadas
create table season(
  Id int generated by default as identity primary key,
  Name varchar(50) not null unique,
  DateStart timestamp(6) not null,
  DateEnd timestamp(6) not null,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now()
);

--tabla de partidos
create table match(
  Id int generated by default as identity primary key,
  SeasonId int not null,
  TournamentId int not null,
  DatePlayed timestamp(6) not null,
  QuantityPlayers int not null check(QuantityPlayers >= 0) default 0,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now(),
  foreign key (SeasonId) references season(Id) on delete cascade,
  foreign key (TournamentId) references tournament(Id) on delete cascade
);



/* intermedias */

--tabla de subtipos de posiciones
create table position_subtype(
  Id int generated by default as identity primary key,
  PositionId int not null,
  Name varchar(50) not null unique,
  foreign key (PositionId) references position(Id)
);

--tabla de usuarios_roles
create table user_role(
  Id int generated by default as identity primary key,
  UserId int not null,
  RoleId int not null,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now(),
  foreign key (UserId) references "user"(Id) on delete cascade,
  foreign key (RoleId) references role(Id) on delete cascade
);

--tabla de perfil de usuario
create table user_profile(
  Id int generated by default as identity primary key,
  UserId int not null unique,
  Name varchar(50) not null,
  Lastname varchar(50) not null,
  Age int check(Age between 18 and 60),
  Image varchar(255),
  PositionPrincipalId int not null,
  SubtypePositionPrincipalId int not null,
  PositionAlternativeId int not null,
  SubtypePositionAlternativeId int not null,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now(),
  foreign key (UserId) references "user"(Id) on delete cascade,
  foreign key (PositionPrincipalId) references position(Id),
  foreign key (SubtypePositionPrincipalId) references position_subtype(Id),
  foreign key (PositionAlternativeId) references position(Id),
  foreign key (SubtypePositionAlternativeId) references position_subtype(Id)
);

--tabla de tipos de torneos
create table type_tournament(
  Id int generated by default as identity primary key,
  Name varchar(50) not null unique
);

--tabla de complementos del torneo
create table tournament_complement(
  Id int generated by default as identity primary key,
  TournamentId int not null,
  QuantityMatches int not null check(QuantityMatches >= 0),
  QuatityTeams int not null check(QuatityTeams >= 0),
  QuantityPlayers int not null check(QuantityPlayers >= 0),
  TypeTournament smallint not null check(TypeTournament between 1 and 6),
  SeasonId int not null,
  CreatedAt timestamp(6) not null default now(),
  UpdatedAt timestamp(6) not null default now(),
  foreign key (TournamentId) references tournament(Id),
  foreign key (TypeTournament) references type_tournament(Id),
  foreign key (SeasonId) references season(Id)
);