-- Limpieza de tblas si existen
drop table if exists match;
drop table if exists season;
drop table if exists group;
drop table if exists role;
drop table if exists "user";
drop table if exists position;
drop table if exists position_subtype;
drop table if exists user_group;
drop table if exists group_admin;
drop table if exists group_season;


/*
* Tablas principales de la base de datos
*/

-- Tabla de partidos
create table match(
	Id int generated by default as identity primary key,
	SeasonId int not null,
	GroupId int not null,
	DatePlayed timestamp(6) not null,
	QuantityPlayers int not null,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (SeasonId) references season(Id) on delete cascade,
	foreign key (GroupId) references group(Id) on delete cascade
)

-- Tabla de temporadas
create table season(
	Id int generated by default as identity primary key,
	Name varchar(50) not null unique,
	StartDate timestamp(6) not null,
	EndDate timestamp(6) not null,
	Availability smallint default 1,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now()
);

-- Tabla de grupos de jugadores
create table group(
	Id int generated by default as identity primary key,
	Name varchar(50) not null unique,
	Availability smallint default 1,
	Image varchar(255),
	QuantityPlayers int not null check(QuantityPlayers >= 0) default 0,
	ValuePerformance smallint default 0 check(ValuePerformance between 0 and 10),
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now()
);

create table role(
	Id int generated by default as identity primary key,
	Name varchar(50) not null unique
);

create table position(
	Id int generated by default as identity primary key,
	Name varchar(50) not null unique,
	Description text
);

create table position_subtype(
	Id int generated by default as identity primary key,
	PositionId int not null,
	Name varchar(50) not null unique,
	foreign key (PositionId) references position(Id)
); 

create table "user"(
	Id varchar(36) primary key not null,
	Username varchar(20) unique not null,
	Password varchar(61) not null,
	RolId int not null,
	Availability smallint default 1,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (RolId) references role(Id) on delete cascade
);

/*
* Tablas auxiliares
*/

-- Tabla de perfil de jugador
create table user_profile(
	Id int generated by default as identity primary key,
	UserId varchar(36) not null unique,
	Name varchar(50) not null,
	Lastname varchar(50) not null,
	Age int check(Age between 18 and 60),
	Image varchar(255),
	PositionPrincipalId int not null,
	SubtypePositionPrincipalId int not null,
	PositionAlternativeId int not null,
	SubtypePositionAlternativeId int not null,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (UserId) references "user"(Id) on delete cascade,
	foreign key (PositionPrincipalId) references position(Id),
	foreign key (SubtypePositionPrincipalId) references position_subtype(Id),
	foreign key (PositionAlternativeId) references position(Id),
	foreign key (SubtypePositionAlternativeId) references position_subtype(Id)
);

create table user_statistic(
	Id int generated by default as identity primary key,
	UserId varchar(36) not null unique,
	MatchesPlayed smallint default 0 check(MatchesPlayed >= 0),
	GoalScored smallint default 0 check(GoalScored >= 0),
	BestPlayerVotes smallint default 0 check(BestPlayerVotes >= 0),
	WortPlayerVotes smallint default 0 check(WortPlayerVotes >= 0),
	ValuePerformance smallint default 0 check(ValuePerformance between 0 and 10),
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (UserId) references "user"(Id) on delete cascade
);

create table user_group(
	Id int generated by default as identity primary key,
	UserId varchar(36) not null unique,
	GroupId int not null,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (UserId) references "user"(Id) on delete cascade,
	foreign key (GroupId) references group(Id) on delete cascade
);

create table group_admin(
	Id int generated by default as identity primary key,
	UserId varchar(36) not null unique,
	GroupId int not null,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (UserId) references "user"(Id) on delete cascade,
	foreign key (GroupId) references group(Id) on delete cascade
);

create table group_season(
	Id int generated by default as identity primary key,
	GroupId int not null,
	SeasonId int not null,
	CreatedAt timestamp(6) not null default now(),
	UpdatedAt timestamp(6) not null default now(),
	foreign key (GroupId) references group(Id) on delete cascade,
	foreign key (SeasonId) references season(Id) on delete cascade
);